# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test package

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:

    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        spark-version: [3.4.0]
        pandas-version: [1.5.3, 1.4.4, 1.5.3]
    env:
      PYTHON_VERSION: ${{ matrix.python-version }} 
      SPARK_VERSION: ${{ matrix.spark-version }}
      PANDAS_VERSION: ${{ matrix.pandas-version }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Install Spark
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-spark pypandoc
        python -m pip install pyspark==${{ matrix.spark-version }}
        python -m pip install pandas==${{ matrix.pandas-version }}
        python -m pip install .[tests]
    - name: Test with pytest
      run: |
        python -m pytest tests/
